"""
=========================================================
CyberScope Report Engine
Author : Krunal Paliwal
=========================================================
"""

from __future__ import annotations

import csv
import json
from pathlib import Path
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.units import inch

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib.styles import getSampleStyleSheet


# ==========================================================
# REPORT ENGINE
# ==========================================================

class ReportEngine:

    def __init__(self):

        self.styles = getSampleStyleSheet()

    # =====================================================

    def export(

        self,

        report_type,

        data,

        output_path

    ):

        report_type = report_type.lower()

        output = Path(output_path)

        output.mkdir(

            parents=True,

            exist_ok=True

        )

        if report_type == "pdf":

            return self.export_pdf(

                data,

                output

            )

        elif report_type == "html":

            return self.export_html(

                data,

                output

            )

        elif report_type == "json":

            return self.export_json(

                data,

                output

            )

        elif report_type == "csv":

            return self.export_csv(

                data,

                output

            )

        raise ValueError(

            "Unknown Report Type"

        )

    # =====================================================

    def filename(

        self,

        extension

    ):

        now = datetime.now()

        return f"CyberScope_{now.strftime('%Y%m%d_%H%M%S')}.{extension}"
          # =====================================================
    # PDF REPORT
    # =====================================================

    def export_pdf(self, data, output_dir):

        filename = output_dir / self.filename("pdf")

        document = SimpleDocTemplate(str(filename))

        story = []

        title_style = self.styles["Title"]
        heading_style = self.styles["Heading2"]
        body_style = self.styles["BodyText"]

        story.append(
            Paragraph(
                "CyberScope Security Assessment Report",
                title_style
            )
        )

        story.append(Spacer(1, 0.30 * inch))

        story.append(
            Paragraph(
                "<b>Generated By:</b> CyberScope",
                body_style
            )
        )

        story.append(
            Paragraph(
                "<b>Author:</b> Krunal Paliwal",
                body_style
            )
        )

        story.append(
            Paragraph(
                f"<b>Date:</b> {datetime.now()}",
                body_style
            )
        )

        story.append(Spacer(1, 0.30 * inch))

        # ===============================================
        # SUMMARY
        # ===============================================

        story.append(
            Paragraph(
                "Summary",
                heading_style
            )
        )

        summary = data.get(
            "summary",
            "No summary available."
        )

        story.append(
            Paragraph(
                str(summary),
                body_style
            )
        )

        story.append(Spacer(1, 0.25 * inch))

        # ===============================================
        # TARGET INFO
        # ===============================================

        target = data.get("target", "")

        ip = data.get("ip", "")

        risk = data.get("risk", "")

        response = data.get("response", "")

        table_data = [

            ["Target", target],

            ["IP Address", ip],

            ["Risk Score", risk],

            ["Response Time", response]

        ]

        table = Table(

            table_data,

            colWidths=[2.2 * inch, 4.5 * inch]

        )

        table.setStyle(

            TableStyle([

                ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#0f172a")),

                ("TEXTCOLOR",(0,0),(-1,-1),colors.white),

                ("GRID",(0,0),(-1,-1),1,colors.gray),

                ("BACKGROUND",(0,1),(-1,-1),colors.HexColor("#1e293b")),

                ("FONTNAME",(0,0),(-1,-1),"Helvetica"),

                ("BOTTOMPADDING",(0,0),(-1,-1),10)

            ])

        )

        story.append(table)

        story.append(Spacer(1,0.30*inch))

        # ===============================================
        # ALL RESULTS
        # ===============================================

        story.append(

            Paragraph(

                "Reconnaissance Results",

                heading_style

            )

        )

        ignore = {

            "summary",

            "target",

            "ip",

            "risk",

            "response"

        }

        for key, value in data.items():

            if key in ignore:

                continue

            story.append(

                Paragraph(

                    f"<b>{key.upper()}</b>",

                    body_style

                )

            )

            story.append(

                Paragraph(

                    "<font face='Courier'>"

                    + str(value).replace("\n","<br/>")

                    + "</font>",

                    body_style

                )

            )

            story.append(

                Spacer(

                    1,

                    0.12 * inch

                )

            )

        # ===============================================
        # FOOTER
        # ===============================================

        story.append(

            Spacer(

                1,

                0.4 * inch

            )

        )

        story.append(

            Paragraph(

                "<b>CyberScope Professional Security Toolkit</b>",

                heading_style

            )

        )

        story.append(

            Paragraph(

                "Generated automatically for defensive security assessment purposes.",

                body_style

            )

        )

        document.build(story)

        return str(filename)
          # =====================================================
    # HTML REPORT
    # =====================================================

    def export_html(self, data, output_dir):

        filename = output_dir / self.filename("html")

        html = f"""
<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="UTF-8">

<title>CyberScope Report</title>

<style>

body{

background:#0f172a;

font-family:Arial;

color:white;

padding:40px;

}

.container{

width:95%;

margin:auto;

}

.card{

background:#1e293b;

padding:20px;

margin-bottom:20px;

border-radius:12px;

box-shadow:0px 0px 15px rgba(0,0,0,.35);

}

table{

width:100%;

border-collapse:collapse;

margin-top:15px;

}

th{

background:#2563eb;

padding:12px;

}

td{

padding:10px;

border-bottom:1px solid #334155;

}

h1{

color:#38bdf8;

}

h2{

color:#60a5fa;

}

.footer{

text-align:center;

margin-top:40px;

font-size:13px;

color:#94a3b8;

}

</style>

</head>

<body>

<div class="container">

<h1>CyberScope Security Report</h1>

<div class="card">

<h2>Summary</h2>

<p>{data.get("summary","No Summary")}</p>

</div>

<div class="card">

<h2>Target Information</h2>

<table>

<tr>

<th>Field</th>

<th>Value</th>

</tr>

<tr>

<td>Target</td>

<td>{data.get("target","")}</td>

</tr>

<tr>

<td>IP</td>

<td>{data.get("ip","")}</td>

</tr>

<tr>

<td>Risk Score</td>

<td>{data.get("risk","")}</td>

</tr>

<tr>

<td>Response Time</td>

<td>{data.get("response","")}</td>

</tr>

</table>

</div>

<div class="card">

<h2>Scan Results</h2>

<table>

<tr>

<th>Module</th>

<th>Output</th>

</tr>
"""

        ignore = {

            "summary",

            "target",

            "ip",

            "risk",

            "response"

        }

        for key, value in data.items():

            if key in ignore:

                continue

            html += f"""

<tr>

<td>{key}</td>

<td><pre>{value}</pre></td>

</tr>

"""

        html += """

</table>

</div>

<div class="footer">

CyberScope Professional Website Recon Toolkit

<br><br>

Generated Automatically

</div>

</div>

</body>

</html>

"""

        with open(

            filename,

            "w",

            encoding="utf-8"

        ) as file:

            file.write(html)

        return str(filename)

    # =====================================================
    # JSON REPORT
    # =====================================================

    def export_json(self, data, output_dir):

        filename = output_dir / self.filename("json")

        with open(

            filename,

            "w",

            encoding="utf-8"

        ) as file:

            json.dump(

                data,

                file,

                indent=4,

                default=str

            )

        return str(filename)

    # =====================================================
    # CSV REPORT
    # =====================================================

    def export_csv(self, data, output_dir):

        filename = output_dir / self.filename("csv")

        with open(

            filename,

            "w",

            newline="",

            encoding="utf-8"

        ) as file:

            writer = csv.writer(file)

            writer.writerow([

                "Module",

                "Result"

            ])

            for key, value in data.items():

                writer.writerow([

                    key,

                    str(value)

                ])

        return str(filename)
      import zipfile
from pathlib import Path


    # =====================================================
    # EXPORT ALL REPORTS
    # =====================================================

    def export_all(self, data, output_path):

        reports = {}

        reports["pdf"] = self.export_pdf(
            data,
            output_path
        )

        reports["html"] = self.export_html(
            data,
            output_path
        )

        reports["json"] = self.export_json(
            data,
            output_path
        )

        reports["csv"] = self.export_csv(
            data,
            output_path
        )

        return reports


    # =====================================================
    # CREATE ZIP
    # =====================================================

    def create_zip(self, reports, output_path):

        zip_file = Path(output_path) / self.filename("zip")

        with zipfile.ZipFile(

            zip_file,

            "w",

            zipfile.ZIP_DEFLATED

        ) as archive:

            for report in reports.values():

                archive.write(

                    report,

                    arcname=Path(report).name

                )

        return str(zip_file)


    # =====================================================
    # REPORT STATISTICS
    # =====================================================

    def statistics(self, data):

        stats = {

            "total_modules": len(data),

            "generated": datetime.now().strftime(
                "%Y-%m-%d %H:%M:%S"
            ),

            "report_version": "2.0",

            "engine": "CyberScope"

        }

        return stats


    # =====================================================
    # VALIDATE REPORT
    # =====================================================

    def validate(self, data):

        if not isinstance(data, dict):

            raise ValueError(
                "Report data must be a dictionary."
            )

        if len(data) == 0:

            raise ValueError(
                "No report data available."
            )

        return True


    # =====================================================
    # SAVE INDEX
    # =====================================================

    def save_index(self, reports, output_path):

        index = {

            "generated": datetime.now().isoformat(),

            "reports": reports

        }

        index_file = Path(output_path) / "report_index.json"

        with open(

            index_file,

            "w",

            encoding="utf-8"

        ) as file:

            json.dump(

                index,

                file,

                indent=4

            )

        return str(index_file)


# ==========================================================
# SELF TEST
# ==========================================================

def self_test():

    sample = {

        "target": "example.com",

        "ip": "93.184.216.34",

        "risk": 18,

        "summary": "Sample report"

    }

    engine = ReportEngine()

    print("Report Engine Loaded")

    print(engine.statistics(sample))


# ==========================================================
# MAIN
# ==========================================================

if __name__ == "__main__":

    self_test()
